/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Class_10_autoincrement;

import C_7_Insert.*;
import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nazirul
 */
public class AutoIncrement extends javax.swing.JFrame {

    Connection ct = null;
    PreparedStatement ps = null;
    Statement st = null;
    ResultSet rs = null;

    public AutoIncrement() {
        initComponents();
        SelectAllData();
        autoCount();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        id_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mail_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pass_txt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setText("Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 120, 110, 30);

        name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_txtActionPerformed(evt);
            }
        });
        jPanel1.add(name_txt);
        name_txt.setBounds(50, 150, 210, 30);

        id_txt.setEditable(false);
        id_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_txtActionPerformed(evt);
            }
        });
        jPanel1.add(id_txt);
        id_txt.setBounds(50, 90, 210, 30);

        jLabel2.setText("ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 60, 110, 30);

        jLabel3.setText("Mail");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 180, 110, 30);

        mail_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mail_txtActionPerformed(evt);
            }
        });
        jPanel1.add(mail_txt);
        mail_txt.setBounds(50, 210, 210, 30);

        jLabel4.setText("Password");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 240, 110, 30);

        pass_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_txtActionPerformed(evt);
            }
        });
        jPanel1.add(pass_txt);
        pass_txt.setBounds(50, 270, 210, 30);

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(50, 330, 200, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Mail", "Password"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(300, 70, 370, 402);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 710, 550);

        setSize(new java.awt.Dimension(749, 560));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// submit

        if (id_txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Id IS empty......");
            id_txt.requestFocus();
        } else if (name_txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Name IS EMpty");
            name_txt.requestFocus();
        } else if (mail_txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Mail IS EMpty");
            mail_txt.requestFocus();
        } else if (pass_txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Pass IS EMpty");
            pass_txt.requestFocus();
        } else {
            try {
                contest();
                String inQueary = "INSERT INTO `registration` (`id`,`name`,`mail`,`password`) VALUES (?,?,?,?)";
                ps = ct.prepareCall(inQueary);
                ps.setString(1, id_txt.getText());
                ps.setString(2, name_txt.getText());
                ps.setString(3, mail_txt.getText());
                ps.setString(4, pass_txt.getText());
                int m = ps.executeUpdate();
                if (m > 0) {
                    JOptionPane.showMessageDialog(rootPane, "Success");
                    SelectAllData();
                    autoCount();
                    clearDAta();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Failed");

                }
            } catch (SQLException ex) {
                Logger.getLogger(AutoIncrement.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void id_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_txtActionPerformed

    private void name_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_txtActionPerformed

    private void mail_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mail_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mail_txtActionPerformed

    private void pass_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_txtActionPerformed
 void clearDAta(){
     name_txt.setText("");
     mail_txt.setText("");
     pass_txt.setText("");
 }
    void SelectAllData() {
        try {
            DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
            dt.setRowCount(0);
            String selectQueary = " SELECT `id`,`name`,`mail`,`password` FROM `registration`";
            contest();
            st = ct.prepareCall(selectQueary);
            rs = st.executeQuery(selectQueary);
            while (rs.next()) {
                dt.addRow(new Object[]{
                    rs.getInt(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4)
                });

            }
        } catch (SQLException ex) {
            Logger.getLogger(AutoIncrement.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    void autoCount() {
        int c = 0;
        try {
            contest();
            String idSelect = " SELECT `id`  FROM `registration`";
            st = ct.prepareCall(idSelect);
            rs = st.executeQuery(idSelect);
            while (rs.next()) {
               c =rs.getInt(1);
            }
            c++;
            id_txt.setText(""+c);
        } catch (SQLException ex) {
            Logger.getLogger(AutoIncrement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void contest() {
        try {
            ct = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/myinfo", "root", "");
        } catch (SQLException ex) {
            Logger.getLogger(AutoIncrement.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutoIncrement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutoIncrement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutoIncrement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutoIncrement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutoIncrement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField id_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField mail_txt;
    private javax.swing.JTextField name_txt;
    private javax.swing.JTextField pass_txt;
    // End of variables declaration//GEN-END:variables
}
