/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package basicTools;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Nazirul
 */
public class AddDuplicate extends javax.swing.JFrame {

    /**
     * Creates new form Add
     */
    public AddDuplicate() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        res = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        val2 = new javax.swing.JTextField();
        val1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        ress = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        res.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        res.setForeground(new java.awt.Color(51, 51, 255));
        res.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        res.setText(" ");
        getContentPane().add(res);
        res.setBounds(110, 310, 280, 56);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enter 2nd Value");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 160, 170, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Enter 1st Value");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 110, 170, 40);

        val2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                val2ActionPerformed(evt);
            }
        });
        val2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                val2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                val2KeyTyped(evt);
            }
        });
        getContentPane().add(val2);
        val2.setBounds(220, 160, 230, 40);

        val1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                val1ActionPerformed(evt);
            }
        });
        val1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                val1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                val1KeyTyped(evt);
            }
        });
        getContentPane().add(val1);
        val1.setBounds(220, 110, 230, 40);

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(340, 260, 130, 30);

        ress.setText("Add");
        ress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ressActionPerformed(evt);
            }
        });
        getContentPane().add(ress);
        ress.setBounds(40, 260, 130, 30);

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(190, 260, 130, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(" Add two Numbers");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 40, 280, 56);

        setSize(new java.awt.Dimension(522, 392));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ressActionPerformed
        // Add

//     if(val1.getTest().isEmpty()){
//     ress.setText("Enter 1st value");
//     }
//     else if(val2.getTest().isEmpty()){
//     ress.setText("Enter 2nd value");
//     val2.requestFocus();
//     }else{ }
        int x = Integer.parseInt(val1.getText().toString());
        int y = Integer.parseInt(val2.getText().toString());
        x = x + y;
        res.setText("Add Result is=" + x);
        cl_all();

    }//GEN-LAST:event_ressActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//clear
        cl_all();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void val1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_val1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_val1ActionPerformed

    void cl_all() {

        val1.setText("");
        val2.setText("");
        val1.requestFocus();
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//exit
//this.dispose();
        System.exit(0);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void val2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_val2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_val2ActionPerformed

    private void val1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_val1KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE) {
            evt.consume();
        }


    }//GEN-LAST:event_val1KeyTyped

    private void val2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_val2KeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE) {
            evt.consume();
        }


    }//GEN-LAST:event_val2KeyTyped

    private void val2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_val2KeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int x = Integer.parseInt(val1.getText().toString());
            int y = Integer.parseInt(val2.getText().toString());
            x = x + y;
            res.setText("Add Result is=" + x);
            cl_all();
        }

    }//GEN-LAST:event_val2KeyPressed

    private void val1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_val1KeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           val2.requestFocus();
       }
    }//GEN-LAST:event_val1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDuplicate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDuplicate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDuplicate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDuplicate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDuplicate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel res;
    private javax.swing.JButton ress;
    private javax.swing.JTextField val1;
    private javax.swing.JTextField val2;
    // End of variables declaration//GEN-END:variables
}
