/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Component_C_3;

import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Nazirul
 */
public class NewJFrame extends javax.swing.JFrame {
 
   String name,skill="",gen,dep;
    public NewJFrame() {
        initComponents();
    }
void showAllVal(){
if(jTextField1.getText().toString().isEmpty()){
JOptionPane.showMessageDialog(this,"Enter Name");
jTextField1.requestFocus();

}else if(jComboBox1.getSelectedIndex()==0){
JOptionPane.showMessageDialog(this,"Select Department");    
jComboBox1.requestFocus();

}else if(rm.isSelected()==false && rf.isSelected()==false){
JOptionPane.showMessageDialog(this,"Select Gendar");    
rm.requestFocus();

}else{
  skill="";
name=jTextField1.getText().toString();
dep=jComboBox1.getSelectedItem().toString();
if(rm.isSelected()){
gen=rm.getText().toString();
}else if(rf.isSelected()){
gen=rf.getText().toString();
}else{
gen=null;
}

  for (int i =0; i < skillpanel.getComponentCount(); i++) {
  JCheckBox jc=(JCheckBox)skillpanel.getComponent(i);
  if(jc.isSelected()){
  skill +=" "+jc.getText();
  }
  }
  skill+=".";
}
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        rf = new javax.swing.JRadioButton();
        rm = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        skillpanel = new javax.swing.JPanel();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));
        jPanel1.setLayout(null);

        jLabel1.setText("Skills");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 150, 140, 30);

        jTextField1.setText(" ");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(130, 30, 180, 30);

        jLabel2.setText("Enter Name:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 30, 140, 30);

        jComboBox1.setEditable(true);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "CST", "TCT", "DNT", "CSE" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(130, 70, 180, 30);

        jLabel3.setText("Depertment");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 70, 140, 30);

        buttonGroup1.add(rf);
        rf.setText("Female");
        rf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfActionPerformed(evt);
            }
        });
        jPanel1.add(rf);
        rf.setBounds(280, 110, 98, 21);

        buttonGroup1.add(rm);
        rm.setText("Male");
        rm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmActionPerformed(evt);
            }
        });
        jPanel1.add(rm);
        rm.setBounds(170, 110, 49, 21);

        jLabel4.setText("Gander");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 110, 140, 30);

        skillpanel.setBackground(new java.awt.Color(204, 204, 255));
        skillpanel.setLayout(null);

        jCheckBox11.setText("Python");
        skillpanel.add(jCheckBox11);
        jCheckBox11.setBounds(220, 10, 100, 30);

        jCheckBox2.setText("C");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        skillpanel.add(jCheckBox2);
        jCheckBox2.setBounds(10, 10, 100, 30);

        jCheckBox22.setText("Java");
        skillpanel.add(jCheckBox22);
        jCheckBox22.setBounds(110, 10, 100, 30);

        jCheckBox4.setText("Dart");
        skillpanel.add(jCheckBox4);
        jCheckBox4.setBounds(10, 50, 100, 30);

        jCheckBox5.setText("JavaScript");
        skillpanel.add(jCheckBox5);
        jCheckBox5.setBounds(110, 50, 100, 30);

        jCheckBox6.setText("Flutter");
        skillpanel.add(jCheckBox6);
        jCheckBox6.setBounds(220, 50, 100, 30);

        jPanel1.add(skillpanel);
        skillpanel.setBounds(100, 160, 360, 100);

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(270, 280, 80, 30);

        jButton2.setText("Show");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(90, 280, 80, 30);

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(180, 280, 80, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 20, 570, 340);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 380, 490, 160);

        setSize(new java.awt.Dimension(732, 605));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void rmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rmActionPerformed

    private void rfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rfActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // show
        showAllVal();
        if(skill.equals(".")){
        skillpanel.requestFocus();
        JOptionPane.showMessageDialog(this,"Select Skill");
        }else{
        jTextArea1.setText("Name:"+name+"\nDepartment:"+dep+"\nGendar:"+gen+"\nSkills:"+skill);
        
    }//GEN-LAST:event_jButton2ActionPerformed
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    void data_clr(){
    jTextField1.setText("");
    jComboBox1.setSelectedIndex(0);
    buttonGroup1.clearSelection();
    
        for (int i = 0; i < skillpanel.getComponentCount(); i++) {
        JCheckBox jc=(JCheckBox)skillpanel.getComponent(i);
         if(jc.isSelected()){
         jc.setSelected(false);
         }
        }
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 // clear
  
data_clr();

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton rf;
    private javax.swing.JRadioButton rm;
    private javax.swing.JPanel skillpanel;
    // End of variables declaration//GEN-END:variables
}
