/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bloodmanagmentsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nazirul
 */
public class Patient extends javax.swing.JFrame {

    Connection ct = null;
    PreparedStatement ps = null;
    Statement st = null;
    ResultSet rs = null;
 
    String id, name, age, gender, bloodgroup,contact,address,addresshos,type_of_dis,hemoglobin,blood_quantity;
    private String selecteQuery;

    
    public Patient() {
        initComponents();
        selectID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        age_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        contact_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        address_txt = new javax.swing.JTextField();
        addhos_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        typeof_txt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        hemoglobin_txt = new javax.swing.JTextField();
        bquantity_txt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        rf = new javax.swing.JRadioButton();
        rm = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Patient Information");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(450, 20, 430, 50);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Donar ID Select      :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 100, 180, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name                     :  ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 140, 180, 30);

        name_txt.setText(" ");
        name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_txtActionPerformed(evt);
            }
        });
        jPanel1.add(name_txt);
        name_txt.setBounds(220, 140, 200, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" Age                        :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 180, 180, 30);

        age_txt.setText(" ");
        age_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                age_txtActionPerformed(evt);
            }
        });
        jPanel1.add(age_txt);
        age_txt.setBounds(220, 180, 200, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gender                   :  ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 220, 180, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("BloodGroup          :  ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 260, 180, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contact                  :  ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 300, 180, 30);

        contact_txt.setText(" ");
        contact_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact_txtActionPerformed(evt);
            }
        });
        jPanel1.add(contact_txt);
        contact_txt.setBounds(220, 300, 200, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Address                  :  ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 340, 180, 30);

        address_txt.setText(" ");
        address_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_txtActionPerformed(evt);
            }
        });
        jPanel1.add(address_txt);
        address_txt.setBounds(220, 340, 200, 30);

        addhos_txt.setText(" ");
        addhos_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addhos_txtActionPerformed(evt);
            }
        });
        jPanel1.add(addhos_txt);
        addhos_txt.setBounds(220, 380, 200, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Address  Hospital :  ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 380, 180, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Donar_ID_Select", "Name", "Age", "Gender", "BloodGroup", "Contact", "Address", "Add Hospital", "Type of Dis", "Hemoglobin", "Blood Quantity"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(430, 100, 720, 402);

        jButton1.setBackground(new java.awt.Color(0, 102, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(630, 570, 250, 50);

        jButton2.setText("Show");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(270, 570, 150, 50);

        jButton3.setBackground(new java.awt.Color(204, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(460, 570, 150, 50);

        typeof_txt.setText(" ");
        typeof_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeof_txtActionPerformed(evt);
            }
        });
        jPanel1.add(typeof_txt);
        typeof_txt.setBounds(220, 420, 200, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Type of Dis            :  ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(50, 420, 180, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Hemoglobin         :  ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(50, 460, 180, 30);

        hemoglobin_txt.setText(" ");
        hemoglobin_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hemoglobin_txtActionPerformed(evt);
            }
        });
        jPanel1.add(hemoglobin_txt);
        hemoglobin_txt.setBounds(220, 460, 200, 30);

        bquantity_txt.setText(" ");
        bquantity_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bquantity_txtActionPerformed(evt);
            }
        });
        jPanel1.add(bquantity_txt);
        bquantity_txt.setBounds(220, 500, 200, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Blood Quantity    :  ");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(50, 500, 180, 30);

        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(100, 570, 150, 50);

        buttonGroup1.add(rf);
        rf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rf.setForeground(new java.awt.Color(255, 255, 255));
        rf.setText("Female");
        rf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfActionPerformed(evt);
            }
        });
        jPanel1.add(rf);
        rf.setBounds(310, 220, 100, 30);

        buttonGroup1.add(rm);
        rm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rm.setForeground(new java.awt.Color(255, 255, 255));
        rm.setText("Male");
        rm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmActionPerformed(evt);
            }
        });
        jPanel1.add(rm);
        rm.setBounds(220, 220, 100, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-", " " }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(220, 252, 200, 40);

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(220, 100, 200, 30);

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 0, 0));
        jButton5.setText("X");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(1050, 30, 50, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1160, 650);

        setSize(new java.awt.Dimension(1161, 663));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void name_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_txtActionPerformed

    private void age_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_age_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_age_txtActionPerformed

    private void contact_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contact_txtActionPerformed

    private void address_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_txtActionPerformed

    private void addhos_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addhos_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addhos_txtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // update
       if (jComboBox2.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "DonerID IS EMpty");
            jComboBox2.requestFocus();
        } else if (name_txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Name IS EMpty");
            name_txt.requestFocus();
        } else if (age_txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Age IS EMpty");
            age_txt.requestFocus();
            
        } else if (rm.isSelected() == false && rf.isSelected() == false) {
            JOptionPane.showMessageDialog(rootPane, "Gender IS EMpty");
            rm.requestFocus();
            
        }else if (jComboBox1.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "DonerID IS EMpty");
            jComboBox1.requestFocus();
        } else if (contact_txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Mobile IS EMpty");
            contact_txt.requestFocus();
        } else if (address_txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Address IS EMpty");
            address_txt.requestFocus();
        } else if (addhos_txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Address IS EMpty");
            addhos_txt.requestFocus();
        } else if (typeof_txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Address IS EMpty");
            typeof_txt.requestFocus();
        } else if (hemoglobin_txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Address IS EMpty");
            hemoglobin_txt.requestFocus();
        } else if (bquantity_txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Address IS EMpty");
            bquantity_txt.requestFocus();
         } else {
            try {
               contest();
             String id=(String) jComboBox2.getSelectedItem();
             String namee=name_txt.getText();
             int agee=Integer.parseInt(age_txt.getText());
                String gen; 
               if(rm.isSelected()){
            gen=rm.getText().toString();
            }else if(rf.isSelected()){
            gen=rf.getText().toString();
            }else{
            gen=null;
            }
             String bg=(String) jComboBox1.getSelectedItem();
           
               int mob=Integer.parseInt(contact_txt.getText());
               String add= address_txt.getText();
               String addH= addhos_txt.getText();
               String type= typeof_txt.getText();
               String homog= hemoglobin_txt.getText();
               int bq=Integer.parseInt(bquantity_txt.getText());
               
                String inserQ = "UPDATE `blood_management`.`Patient`SET `ID` = '"+id+"',`Name` = '"+namee+"',`Age` = '"+agee+"',`Gender` = '"+gen+"',`BloodGroup` = '"+bg+"',`Contact` = '"+mob+"',`Address` = '"+add+"',`addressHospital` = '"+addH+"',`type_of_dis` = '"+type+"',`hemoglobin`='"+homog+"',`bquantity` = '"+bq+"'WHERE `ID` = '"+id+"'";
                ps = ct.prepareCall(inserQ);
                int m = ps.executeUpdate();
                if (m > 0) {

                    JOptionPane.showMessageDialog(rootPane, "Success");
                    selectAllData();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Faild");
                }

            } catch (SQLException ex) {
                Logger.getLogger(Doner.class.getName()).log(Level.SEVERE, null, ex);
            }                 
        }
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // clear
        
        data_clr();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void typeof_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeof_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeof_txtActionPerformed

    private void hemoglobin_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hemoglobin_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hemoglobin_txtActionPerformed

    private void bquantity_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bquantity_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bquantity_txtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // show:
        
          selectAllData();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // add button
        
           if (jComboBox2.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Select Donar Id IS EMpty");
            jComboBox2.requestFocus();
        } else if (name_txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Name IS EMpty");
            name_txt.requestFocus();
        } else if (age_txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Age IS EMpty");
            age_txt.requestFocus();
       } else if (rm.isSelected() == false && rf.isSelected() == false) {
            JOptionPane.showMessageDialog(rootPane, "Gender IS EMpty");
            rm.requestFocus(); 
         
        } else if (jComboBox1.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "BloodGrour IS EMpty");
            jComboBox1.requestFocus();
        } else if (contact_txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Contact IS EMpty");
            contact_txt.requestFocus();
       } else if (address_txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Address IS EMpty");
            address_txt.requestFocus();
      } else if (typeof_txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Type of Dis IS EMpty");
            typeof_txt.requestFocus();
     } else if (hemoglobin_txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Hemoglobin IS EMpty");
            hemoglobin_txt.requestFocus();
     } else if (bquantity_txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Blood Quantity IS EMpty");
            bquantity_txt.requestFocus();
         
        } else {
            try {
               contest();
               String gen; 
               if(rm.isSelected()){
            gen=rm.getText().toString();
            }else if(rf.isSelected()){
            gen=rf.getText().toString();
            }else{
            gen=null;  }
               
                String inserQ = "INSERT INTO `patient`(`Donar_ID_Select`,`NAME`,`Age`,`Gender`,`BloodGroup`,`Contact`,`Address`,`Address_Hospital`,`Type_Of_dis`,`Hemoglobin`,`Blood_Quantity`)VALUES "
                        + "('" + jComboBox2.getSelectedItem() + "','" + "','" + name_txt.getText() + "','" + age_txt.getText()+ "','" + gen + "','" + jComboBox1.getSelectedItem() + "','" + contact_txt.getText() + "','" + address_txt.getText() + "','" +addhos_txt.getText() + "','" +typeof_txt.getText() + "','" +hemoglobin_txt.getText() + "','" +bquantity_txt.getText() + "')";
             
                ps = ct.prepareCall(inserQ);
                int m = ps.executeUpdate();
                if (m > 0){

                    JOptionPane.showMessageDialog(rootPane, "Success");
                    selectAllData();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Faild");
                }

            } catch (SQLException ex) {
                Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
            }
 
           
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            if (dtm.getRowCount() <= 0) {
                dtm.addRow(new Object[]{id, name, age, gender, bloodgroup,contact,address,addresshos,type_of_dis,hemoglobin,blood_quantity});
            }
        }   
    }//GEN-LAST:event_jButton4ActionPerformed

    
    
      void selectAllData() {

        try{
            contest();
             DefaultTableModel dt =(DefaultTableModel) jTable1.getModel();
           dt.setRowCount(0);
            
           String selectQuery = "SELECT `ID`,`NAME`,`Age`,`Gender`,`BloodGroup`,`Contact`,`Address`,`Address_Hospital`,`Type_Of_dis`,`Hemoglobin`,`Blood_Quantity` FROM  `patient`";
           st = ct.prepareCall(selectQuery);
            rs = st.executeQuery(selectQuery);
            while (rs.next()) {
                  
 
            dt.addRow(new Object[]{
                rs.getInt(1),rs.getString(2), rs.getInt(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8), rs.getString(9), rs.getString(10), rs.getString(11) });
            }
        } catch (SQLException ex) {
            Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

void contest(){
        try {
            ct = DriverManager.getConnection("jdbc:mysql://localhost:3306/blood_management", "root", "");
        } catch (SQLException ex) {
            Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
}



   void selectID() {
        try {
            contest();
            String idQueary = "SELECT `ID` FROM `donner`";
            ps = ct.prepareCall(idQueary);
            rs = ps.executeQuery(idQueary);
            while (rs.next()) {
                jComboBox2.addItem("" + rs.getInt(1));
            }

        } catch (SQLException ex) {
            Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

     
    void data_clr(){
    jComboBox2.removeAllItems();
    name_txt.setText("");
    age_txt.setText(""); 
    buttonGroup1.clearSelection();
   jComboBox1.removeAllItems();
    contact_txt.setText("");
    address_txt.setText("");
    addhos_txt.setText("");
    typeof_txt.setText(""); 
    hemoglobin_txt.setText("");
    bquantity_txt.setText("");
    }
        
    
    private void rfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_rfActionPerformed

    private void rmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rmActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // exit 
                this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
         DefaultTableModel dt=(DefaultTableModel) jTable1.getModel();
        jTable1.getModel();
        String id =  dt.getValueAt(jTable1.getSelectedRow(), 0).toString();
        String nama =   dt.getValueAt(jTable1.getSelectedRow(), 1).toString();
        String age =  dt.getValueAt(jTable1.getSelectedRow(), 2).toString();
        String gen =  dt.getValueAt(jTable1.getSelectedRow(), 3).toString();
        String bg =   dt.getValueAt(jTable1.getSelectedRow(), 4).toString();
        String contact =dt.getValueAt(jTable1.getSelectedRow(), 5).toString();
        String add =dt.getValueAt(jTable1.getSelectedRow(), 6).toString();
        String addH =dt.getValueAt(jTable1.getSelectedRow(), 7).toString();
        String type =dt.getValueAt(jTable1.getSelectedRow(), 8).toString();
        String homog =dt.getValueAt(jTable1.getSelectedRow(), 9).toString();
        String bq =dt.getValueAt(jTable1.getSelectedRow(), 10).toString();
        
        jComboBox2.setSelectedItem(id);
        name_txt.setText(nama);
        age_txt.setText(""+age);
           if(rm.getText().equals(gen)){
           rm.setSelected(true);
            }else{
            rf.setSelected(true);
            }
       jComboBox1.setSelectedItem(bg);
         contact_txt.setText(""+contact);
        address_txt.setText(add);
        addhos_txt.setText(addH);
        typeof_txt.setText(type);
        hemoglobin_txt.setText(homog);
        address_txt.setText(add);
        bquantity_txt.setText(""+bq);
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addhos_txt;
    private javax.swing.JTextField address_txt;
    private javax.swing.JTextField age_txt;
    private javax.swing.JTextField bquantity_txt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField contact_txt;
    private javax.swing.JTextField hemoglobin_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField name_txt;
    private javax.swing.JRadioButton rf;
    private javax.swing.JRadioButton rm;
    private javax.swing.JTextField typeof_txt;
    // End of variables declaration//GEN-END:variables
}
